name: Pre Release
on:
  pull_request:
    paths: [CHANGELOG.md]
    branches: [master]
jobs:
  Post-Comment:
    name: Post Comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          source .github/scripts/changelog.sh
          git fetch origin --tags
          if [[ ! -z "$version" && -z "$(git tag -l "v$version")" ]]; then
            echo "BODY<<EOF" >> $GITHUB_ENV
            echo "$(IFS=$'\n'; echo "${log[*]}")" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
            echo "TAG=v$version" >> $GITHUB_ENV
          fi
        shell: bash
      - if: ${{ env.TAG != '' }}
        uses: marocchino/sticky-pull-request-comment@82e7a0d3c51217201b3fedc4ddde6632e969a477 # v2.1.1
        with:
          header: pre-release
          recreate: true
          message: |
            ## ${{ env.TAG }}

            ${{ env.BODY }}
